using System.Collections.ObjectModel;
using AnimeZone.Models;
namespace AnimeZone.Services;

public class AnimeService
{
    public List<Anime> GetAnimeFromType(string pTypeName)
    {
        List<Anime> listAnime = new List<Anime>();

        switch (pTypeName)
        {
            case "Recommended":
                listAnime.Add(new Anime() { Name = "Demon Slayer", Synopsis = "Kamado Tanjiro is a gentle-hearted and intelligent boy. He therefore became the main source of income to support the family after his father died. Everything changes when a demon invades and kills Tanjiro's family. Only him and his younger sister Nezuko are left, who have turned into demons. But it was surprising that she still had human thoughts and expressions. After Tanjiro fought against Tomioka Giyu, a demon hunter who passed by. At Giyu's persuasion, he decided to become a demon hunter. To find a way to turn my sister back into a human being. and take revenge from the demon that killed his family members.", ImgUrl = "https://image.api.playstation.com/vulcan/ap/rnd/202106/1704/JzL1NLQvok7Pghe9W5PP2XNV.png", Tags = "Drama / Action" });
                listAnime.Add(new Anime() { Name = "Spy x Family", Synopsis = "The ultimate spy (Sunthaya) has been ordered to create a family to sneak into a famous school, but the daughter he meets happens to have the power to read people's minds! Wife is an assassin!? A hilarious home comedy of a fake family. that each side conceals the true identity of each other who must face the entrance exam and protect the world", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYWI5NTIxOGQtNzJlNC00YzZlLWI1MzQtMTllNGE5Njk0NDdjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg", Tags = "Comedy" });
                listAnime.Add(new Anime() { Name = "YOASOBI : Idol", Synopsis = "The story tells of Goro, a young doctor in a rural hospital. He has such a passion for his idol, Hoshino Ai, that it could be called crazy. But one day, Goro meets Oshi. (our favorite idols) themselves in unexpected ways Because I had come to this far away hospital for prenatal care. Even though he was shocked at first, when he saw Ai's determination to continue \"lying\" in order to preserve both the idol's life and the lives of his unborn twin children, So he decided to help take care of her. including a promise to deliver the child safely", ImgUrl = "https://i1.sndcdn.com/artworks-nypVxQysyyck8wyt-wSzUwg-t500x500.jpg", Tags = "Idols / Music" });
                break;

            case "Popular":
                listAnime.Add(new Anime() { Name = "Mashle Magic and Muscles", Synopsis = "Magic land A place where anyone can use magic. A place where magical talent determines everything. In that land, Mach, a young boy who trains his body like crazy every day, lives in a forest far away from people. There is one secret. That is, he couldn't use magic. However, when the secret was known to others, Mush's life has completely changed!", ImgUrl = "https://m.media-amazon.com/images/M/MV5BM2M1Yzc5OTMtNWQxYS00NTg5LThiYjQtODRhZGMwODVkNjAyXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg", Tags = "Action / Comedy" });
                listAnime.Add(new Anime() { Name = "Chainsaw Man", Synopsis = "The story of Denji, a poor boy who has to work as a demon hunter to earn money to pay off debts, with Pojita, the adorable chainsaw demon, as his partner. Until one day, Denji fell to a demon and died. Pojita then decides to give his heart to Denji in order to save his life. It was then that Denji transformed into a powerful chainsaw demon.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BZjY5MDFhZTgtOGVhMi00NTUzLTk5NjktNmRlMjI3NjI4MmE0XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_FMjpg_UX1000_.jpg", Tags = "Action" });
                listAnime.Add(new Anime() { Name = "One Piece", Synopsis = "The story of the golden age of pirates The former owner of One Piece Gold D. Roger has surrendered. And accepted the death penalty and before dying Gold D. Roger left words before his death that changed the era of pirates: “My treasure? If you want it, take it. Go find it. I put everything in the world there. The pirates then headed towards the Grand Line to find the One Piece.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BM2YwYTkwNjItNGQzNy00MWE1LWE1M2ItOTMzOGI1OWQyYjA0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg", Tags = "Drama / Comedy / Action" });
                listAnime.Add(new Anime() { Name = "Bleach", Synopsis = "Alarms sounded throughout Seoul. Society seemed to tell something. Then suddenly the people of Lukon disappeared. Meanwhile, in the city of Karakura itself Some shadows silently crawled towards Ichigo's group. The stories slowly come to a conclusion in the final part. Thousand Year Blood War Now the curtain has opened!!", ImgUrl = "https://m.media-amazon.com/images/M/MV5BZjE0YjVjODQtZGY2NS00MDcyLThhMDAtZGQwMTZiOWNmNjRiXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg", Tags = "Action / Adventure" });
                listAnime.Add(new Anime() { Name = "Sword Art Online", Synopsis = "Kirigaya Kazuto joins a virtual reality game called Sword Art Online or SAO. When he plays, he finds himself unable to log out of the game. But the only way out of this game is to successfully clear the game. Or over in the game means the actual death of the player. Therefore, to meet the conditions of clearing this game and leaving the virtual world. Kazuto must clear this game successfully. Or he will meet death!", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYjY4MDU2YjMtNzY1MC00ODg1LWIwMzYtMWE5YTA3YTI4ZjMxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg", Tags = "Fantasy / Adventure / Romance" });
                listAnime.Add(new Anime() { Name = "Jujutsu Kaisen", Synopsis = "Itadori Yuji is a high school student who has high physical ability but avoids sports and joins the supernatural group. He has become involved with “Cursed Item” that causes a monster to appear, Yuji, and swallow the cursed finger to save his friend. But the cursed power of the Demon God's Finger Ryomensukuna was unable to control his body. This made the guild intend for him to collect the cursed fingers of the Asura God. By having him study at a school in Tokyo. Hopefully he could collect all of Sukuna's fingers. Then defeat Yuji later.", ImgUrl = "https://im.uniqlo.com/global-cms/spa/res5275fe1bbcf43ed0ef37283f495cb40dfr.jpg", Tags = "Demons" });
                listAnime.Add(new Anime() { Name = "Attack on Titan", Synopsis = "Humans are nearly exterminated by giant creatures called Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a land protected by extremely high walls, even taller than the biggest of titans. Flash forward to the present, and mankind has not seen a titan in over 100 years. One day, 10 year old Eren and his childhood friend Mikasa witness something horrific as the city walls are destroyed by a colossal titan that appears out of thin air. As the smaller titans flood the city, the two kids watch in horror as Eren's mother is eaten alive. Eren vows that he will murder every single titan and take revenge for all of mankind.", ImgUrl = "https://s.isanook.com/mv/0/ud/10/53513/2.jpg", Tags = "Adventure / Mystery" });
                listAnime.Add(new Anime() { Name = "Horimiya", Synopsis = "At first glance, the ultra-popular Kyoko Hori seems like a frivolous high school girl, but in reality, she's simple, pragmatic, and family-oriented. On the other hand, the bespectacled Miyamura Izumi comes across as an average, gloomy high school fanboy, but he's actually an attractive young man who has a bad-boy streak and is covered in piercings and tattoos. When these two unexpectedly si", ImgUrl = "https://m.media-amazon.com/images/M/MV5BMjBmMzJmN2UtNmEzNC00OGJmLTg4Y2EtMWNjYjlkOTZlZjAyXkEyXkFqcGdeQXVyMTIzNDEwODY@._V1_.jpg", Tags = "School / Romance" });
                break;


            case "Fantasy":
                listAnime.Add(new Anime() { Name = "Mashle Magic and Muscles", Synopsis = "Magic land A place where anyone can use magic. A place where magical talent determines everything. In that land, Mach, a young boy who trains his body like crazy every day, lives in a forest far away from people. There is one secret. That is, he couldn't use magic. However, when the secret was known to others, Mush's life has completely changed!", ImgUrl = "https://m.media-amazon.com/images/M/MV5BM2M1Yzc5OTMtNWQxYS00NTg5LThiYjQtODRhZGMwODVkNjAyXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg", Tags = "Action / Comedy" });
                listAnime.Add(new Anime() { Name = "Chainsaw Man", Synopsis = "The story of Denji, a poor boy who has to work as a demon hunter to earn money to pay off debts, with Pojita, the adorable chainsaw demon, as his partner. Until one day, Denji fell to a demon and died. Pojita then decides to give his heart to Denji in order to save his life. It was then that Denji transformed into a powerful chainsaw demon.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BZjY5MDFhZTgtOGVhMi00NTUzLTk5NjktNmRlMjI3NjI4MmE0XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_FMjpg_UX1000_.jpg", Tags = "Action" });
                listAnime.Add(new Anime() { Name = "Blue Exorcist Shimane Illuminati Saga", Synopsis = "After Okumura Rin and Okumura Yukio defeated the Defilement King of Kyoto. Everything returned to normal. But the Knight Cross Academy constantly heard stories about demons. Moreover, mysterious phenomena occur in various parts of the world. Rin along with the others must work together to solve these mysteries.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BMjA5OTgwNDU4MV5BMl5BanBnXkFtZTcwMDcwMTI4OQ@@._V1_FMjpg_UX1000_.jpg", Tags = "Action" });
                listAnime.Add(new Anime() { Name = "Sasaki to Pii-chan", Synopsis = "The sparrow bought from a pet store is actually a famous sage reincarnated from another world. Sasaki is given the opportunity to cross worlds and has powerful magical powers. So he started a business transporting goods from the present world to sell in other worlds. But one day, he accidentally bumped into someone with special powers. His abilities caught the eye of the Department of Paranormal Phenomenon Control, Office of the Prime Minister instead. Until being invited to work by another party And then he had a chance to change his job to become a full-fledged government official.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BOWQxODhiMGMtOTQ5MC00MGE5LTk5N2YtYzU2OTIzMmViZWNlXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg", Tags = "Comedy" });
                listAnime.Add(new Anime() { Name = "Sword Art Online", Synopsis = "Kirigaya Kazuto joins a virtual reality game called Sword Art Online or SAO. When he plays, he finds himself unable to log out of the game. But the only way out of this game is to successfully clear the game. Or over in the game means the actual death of the player. Therefore, to meet the conditions of clearing this game and leaving the virtual world. Kazuto must clear this game successfully. Or he will meet death!", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYjY4MDU2YjMtNzY1MC00ODg1LWIwMzYtMWE5YTA3YTI4ZjMxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg", Tags = "Action / Adventure / Romance" });
                listAnime.Add(new Anime() { Name = "One Piece", Synopsis = "The story of the golden age of pirates The former owner of One Piece Gold D. Roger has surrendered. And accepted the death penalty and before dying Gold D. Roger left words before his death that changed the era of pirates: “My treasure? If you want it, take it. Go find it. I put everything in the world there. The pirates then headed towards the Grand Line to find the One Piece.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BM2YwYTkwNjItNGQzNy00MWE1LWE1M2ItOTMzOGI1OWQyYjA0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg", Tags = "Drama / Comedy / Action" });
                listAnime.Add(new Anime() { Name = "Bleach", Synopsis = "Alarms sounded throughout Seoul. Society seemed to tell something. Then suddenly the people of Lukon disappeared. Meanwhile, in the city of Karakura itself Some shadows silently crawled towards Ichigo's group. The stories slowly come to a conclusion in the final part. Thousand Year Blood War Now the curtain has opened!!", ImgUrl = "https://m.media-amazon.com/images/M/MV5BZjE0YjVjODQtZGY2NS00MDcyLThhMDAtZGQwMTZiOWNmNjRiXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg", Tags = "Action / Adventure" });
                listAnime.Add(new Anime() { Name = "Bucchigiri?!", Synopsis = "Aragin who has sweet dreams about high school life in a new school. But the reunion of Aragin Tomoshibi and his old friend Matakara Asamine take an unexpected turn when they accidentally get into a fight with a group of the toughest men in town. And when you think about things It won't get any more strange than this. A gigantic giant suddenly appeared.", ImgUrl = "https://news.dexclub.com/wp-content/uploads/2023/11/bucchigiri_kv.jpg", Tags = "Comedy / School" });
                listAnime.Add(new Anime() { Name = "Pokemon", Synopsis = "Ten-year-old Ash aspires to be the greatest Pokémon (Pocket Monster) trainer in the world. To do this, he enlists the help of many friends, and his own Pokémon, Pikachu. Together, they must search their world for new Pokémon, while avoiding the likes of Team Rocket, as well as other evil organizations, as well as battling rivals, and meeting legendary Pokémon", ImgUrl = "https://m.media-amazon.com/images/M/MV5BNDcwZDc2NTEtMzU0Ni00YTQyLWIyYTQtNTI3YjM0MzhmMmI4XkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_FMjpg_UX1000_.jpg", Tags = "Comedy / Action" });
                listAnime.Add(new Anime() { Name = "Kagami no Kojou", Synopsis = "Today is another day that Kokoro doesn't go to school. She kept herself locked in the dim bedroom. Suddenly, the large mirror emitted a strange light. When you reach out to touch She was sucked in. Mr. Anzai Kokoro, congratulations on being a guest of this castle the girl wearing the wolf mask said. At the end of the world behind the glass is a magical castle. There were six other children there who met the same fate as Kokoro. They must find a hidden key. Whoever finds it can make any wish they wish.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYTNmYWIwOWUtNzk0ZC00MjVmLTkyOWYtZGZhYTMwNTAxYTE5XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg", Tags = "Drama / Mystery" });
                listAnime.Add(new Anime() { Name = "Inuyasha", Synopsis = "Inuyasha is a half-demon. This makes Inuyasha unacceptable to both demons and normal humans. As a result, he needed the Four Spirit Orbs to become a full-fledged demon. The orb is protected by Kikyo, the village's sacred miko. Therefore, he and Kikyo often had to compete with each other. But Inuyasha couldn't hurt Kikyo just as Kikyo couldn't hurt Inuyasha either because they both had feelings for each other.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BNjQwZDcxOWYtMTc1ZS00OTYwLThhNmYtMjY3MjgxZGQzYTYzXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg", Tags = "Comedy / Romance / Action" });
                listAnime.Add(new Anime() { Name = "Kamisama Hajimemashita", Synopsis = "The story of Momozono Nanami, a high school girl who is going through a difficult time. Because her father ran away because of gambling debts, she was evicted from her apartment. One day, Nanami met The young man, Mikage, looked suspicious and said, \"I'll give you my house.\" Nanami went to the address she had given her. I found that it was just an abandoned shrine. And in that shrine there is still the young fox god Tomoe.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BZmE2NTBlY2QtNzNjYy00OGIxLTg2YWYtMTk0MWQwNDA2ZWQzXkEyXkFqcGdeQXVyMTUyNjc3NDQ4._V1_FMjpg_UX1000_.jpg", Tags = "Comedy / Romance" });
                break;

            case "Action":
                listAnime.Add(new Anime() { Name = "Mashle Magic and Muscles", Synopsis = "Magic land A place where anyone can use magic. A place where magical talent determines everything. In that land, Mach, a young boy who trains his body like crazy every day, lives in a forest far away from people. There is one secret. That is, he couldn't use magic. However, when the secret was known to others, Mush's life has completely changed!", ImgUrl = "https://m.media-amazon.com/images/M/MV5BM2M1Yzc5OTMtNWQxYS00NTg5LThiYjQtODRhZGMwODVkNjAyXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg", Tags = "Fantasy / Comedy" });
                listAnime.Add(new Anime() { Name = "Chainsaw Man", Synopsis = "The story of Denji, a poor boy who has to work as a demon hunter to earn money to pay off debts, with Pojita, the adorable chainsaw demon, as his partner. Until one day, Denji fell to a demon and died. Pojita then decides to give his heart to Denji in order to save his life. It was then that Denji transformed into a powerful chainsaw demon.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BZjY5MDFhZTgtOGVhMi00NTUzLTk5NjktNmRlMjI3NjI4MmE0XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_FMjpg_UX1000_.jpg", Tags = "Fantasy" });
                listAnime.Add(new Anime() { Name = "Blue Exorcist Shimane Illuminati Saga", Synopsis = "After Okumura Rin and Okumura Yukio defeated the Defilement King of Kyoto. Everything returned to normal. But the Knight Cross Academy constantly heard stories about demons. Moreover, mysterious phenomena occur in various parts of the world. Rin along with the others must work together to solve these mysteries.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BMjA5OTgwNDU4MV5BMl5BanBnXkFtZTcwMDcwMTI4OQ@@._V1_FMjpg_UX1000_.jpg", Tags = "Fantasy" });
                listAnime.Add(new Anime() { Name = "Demon Slayer", Synopsis = "Kamado Tanjiro is a gentle-hearted and intelligent boy. He therefore became the main source of income to support the family after his father died. Everything changes when a demon invades and kills Tanjiro's family. Only him and his younger sister Nezuko are left, who have turned into demons. But it was surprising that she still had human thoughts and expressions. After Tanjiro fought against Tomioka Giyu, a demon hunter who passed by. At Giyu's persuasion, he decided to become a demon hunter. To find a way to turn my sister back into a human being. and take revenge from the demon that killed his family members.", ImgUrl = "https://image.api.playstation.com/vulcan/ap/rnd/202106/1704/JzL1NLQvok7Pghe9W5PP2XNV.png", Tags = "Drama" });
                listAnime.Add(new Anime() { Name = "Spy x Family", Synopsis = "The ultimate spy (Sunthaya) has been ordered to create a family to sneak into a famous school, but the daughter he meets happens to have the power to read people's minds! Wife is an assassin!? A hilarious home comedy of a fake family. that each side conceals the true identity of each other who must face the entrance exam and protect the world", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYWI5NTIxOGQtNzJlNC00YzZlLWI1MzQtMTllNGE5Njk0NDdjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg", Tags = "Comedy" });
                listAnime.Add(new Anime() { Name = "Sword Art Online", Synopsis = "Kirigaya Kazuto joins a virtual reality game called Sword Art Online or SAO. When he plays, he finds himself unable to log out of the game. But the only way out of this game is to successfully clear the game. Or over in the game means the actual death of the player. Therefore, to meet the conditions of clearing this game and leaving the virtual world. Kazuto must clear this game successfully. Or he will meet death!", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYjY4MDU2YjMtNzY1MC00ODg1LWIwMzYtMWE5YTA3YTI4ZjMxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg", Tags = "Fantasy / Adventure / Romance" });
                listAnime.Add(new Anime() { Name = "Jujutsu Kaisen", Synopsis = "Itadori Yuji is a high school student who has high physical ability but avoids sports and joins the supernatural group. He has become involved with “Cursed Item” that causes a monster to appear, Yuji, and swallow the cursed finger to save his friend. But the cursed power of the Demon God's Finger Ryomensukuna was unable to control his body. This made the guild intend for him to collect the cursed fingers of the Asura God. By having him study at a school in Tokyo. Hopefully he could collect all of Sukuna's fingers. Then defeat Yuji later.", ImgUrl = "https://im.uniqlo.com/global-cms/spa/res5275fe1bbcf43ed0ef37283f495cb40dfr.jpg", Tags = "Demons" });
                listAnime.Add(new Anime() { Name = "One Piece", Synopsis = "The story of the golden age of pirates The former owner of One Piece Gold D. Roger has surrendered. And accepted the death penalty and before dying Gold D. Roger left words before his death that changed the era of pirates: “My treasure? If you want it, take it. Go find it. I put everything in the world there. The pirates then headed towards the Grand Line to find the One Piece.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BM2YwYTkwNjItNGQzNy00MWE1LWE1M2ItOTMzOGI1OWQyYjA0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg", Tags = "Drama / Fantasy / Comedy" });
                listAnime.Add(new Anime() { Name = "Attack on Titan", Synopsis = "Humans are nearly exterminated by giant creatures called Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a land protected by extremely high walls, even taller than the biggest of titans. Flash forward to the present, and mankind has not seen a titan in over 100 years. One day, 10 year old Eren and his childhood friend Mikasa witness something horrific as the city walls are destroyed by a colossal titan that appears out of thin air. As the smaller titans flood the city, the two kids watch in horror as Eren's mother is eaten alive. Eren vows that he will murder every single titan and take revenge for all of mankind.", ImgUrl = "https://s.isanook.com/mv/0/ud/10/53513/2.jpg", Tags = "Adventure / Mystery" });
                listAnime.Add(new Anime() { Name = "Bleach", Synopsis = "Alarms sounded throughout Seoul. Society seemed to tell something. Then suddenly the people of Lukon disappeared. Meanwhile, in the city of Karakura itself Some shadows silently crawled towards Ichigo's group. The stories slowly come to a conclusion in the final part. Thousand Year Blood War Now the curtain has opened!!", ImgUrl = "https://m.media-amazon.com/images/M/MV5BZjE0YjVjODQtZGY2NS00MDcyLThhMDAtZGQwMTZiOWNmNjRiXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg", Tags = "Fantasy / Adventure" });
                listAnime.Add(new Anime() { Name = "Pokemon", Synopsis = "Ten-year-old Ash aspires to be the greatest Pokémon (Pocket Monster) trainer in the world. To do this, he enlists the help of many friends, and his own Pokémon, Pikachu. Together, they must search their world for new Pokémon, while avoiding the likes of Team Rocket, as well as other evil organizations, as well as battling rivals, and meeting legendary Pokémon", ImgUrl = "https://m.media-amazon.com/images/M/MV5BNDcwZDc2NTEtMzU0Ni00YTQyLWIyYTQtNTI3YjM0MzhmMmI4XkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_FMjpg_UX1000_.jpg", Tags = "Comedy / Fantasy" });
                listAnime.Add(new Anime() { Name = "Inuyasha", Synopsis = "Inuyasha is a half-demon. This makes Inuyasha unacceptable to both demons and normal humans. As a result, he needed the Four Spirit Orbs to become a full-fledged demon. The orb is protected by Kikyo, the village's sacred miko. Therefore, he and Kikyo often had to compete with each other. But Inuyasha couldn't hurt Kikyo just as Kikyo couldn't hurt Inuyasha either because they both had feelings for each other.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BNjQwZDcxOWYtMTc1ZS00OTYwLThhNmYtMjY3MjgxZGQzYTYzXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg", Tags = "Comedy / Fantasy / Romance" });
                listAnime.Add(new Anime() { Name = "Kyokou Suiri", Synopsis = "When she was still just a girl, Kotoko was kidnapped by the spirits that asked her to become a mediator between the two worlds, as well as the Goddess of Wisdom for these spirits. However, power always comes with a price: an eye and a leg. Now, years later, watching out for dangerous spirits, helping the good spirits, Kotoko meets a mysterious young man named Kurou and immediately takes an interest in him. How can spirits be afraid of a single human and what secrets does Kurou hide?", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYzBmNjIxMDktMjk2MS00MjA0LTljYjQtZWNiYjM2YmU3Y2E1XkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg", Tags = "Mystery" });
                listAnime.Add(new Anime() { Name = "Darwin’s Game", Synopsis = "Darwin's Game focuses on 17-year old Kaname Sudou, who accepts an online invitation from a friend to play a mobile game called Darwin's Game. He had no idea that the game involves a fight between the two players and you might actually die both in the game and in real life. To win the fight, players are given a Sigil, an evolutionary ability that varies from player to player and only the most skillful players will be able to clear the game and survive. Kaname determines to clear the game, find the creators of the game and take revenge upon them.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BNzdhOGUwNjEtNTQyMi00MjkxLThkNDMtYjZiZmVkYWI2NDllXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_FMjpg_UX1000_.jpg", Tags = "Mystery" });
                break;

            case "Comedy":
                listAnime.Add(new Anime() { Name = "Sasaki to Pii-chan", Synopsis = "The sparrow bought from a pet store is actually a famous sage reincarnated from another world. Sasaki is given the opportunity to cross worlds and has powerful magical powers. So he started a business transporting goods from the present world to sell in other worlds. But one day, he accidentally bumped into someone with special powers. His abilities caught the eye of the Department of Paranormal Phenomenon Control, Office of the Prime Minister instead. Until being invited to work by another party And then he had a chance to change his job to become a full-fledged government official.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BOWQxODhiMGMtOTQ5MC00MGE5LTk5N2YtYzU2OTIzMmViZWNlXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg", Tags = "Fantasy" });
                listAnime.Add(new Anime() { Name = "Spy x Family", Synopsis = "The ultimate spy (Sunthaya) has been ordered to create a family to sneak into a famous school, but the daughter he meets happens to have the power to read people's minds! Wife is an assassin!? A hilarious home comedy of a fake family. that each side conceals the true identity of each other who must face the entrance exam and protect the world", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYWI5NTIxOGQtNzJlNC00YzZlLWI1MzQtMTllNGE5Njk0NDdjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg", Tags = "Action" });
                listAnime.Add(new Anime() { Name = "One Piece", Synopsis = "The story of the golden age of pirates The former owner of One Piece Gold D. Roger has surrendered. And accepted the death penalty and before dying Gold D. Roger left words before his death that changed the era of pirates: “My treasure? If you want it, take it. Go find it. I put everything in the world there. The pirates then headed towards the Grand Line to find the One Piece.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BM2YwYTkwNjItNGQzNy00MWE1LWE1M2ItOTMzOGI1OWQyYjA0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg", Tags = "Drama / Fantasy / Action" });
                listAnime.Add(new Anime() { Name = "Bucchigiri?!", Synopsis = "Aragin who has sweet dreams about high school life in a new school. But the reunion of Aragin Tomoshibi and his old friend Matakara Asamine take an unexpected turn when they accidentally get into a fight with a group of the toughest men in town. And when you think about things It won't get any more strange than this. A gigantic giant suddenly appeared.", ImgUrl = "https://news.dexclub.com/wp-content/uploads/2023/11/bucchigiri_kv.jpg", Tags = "Fantasy / School" });
                listAnime.Add(new Anime() { Name = "Pokemon", Synopsis = "Ten-year-old Ash aspires to be the greatest Pokémon (Pocket Monster) trainer in the world. To do this, he enlists the help of many friends, and his own Pokémon, Pikachu. Together, they must search their world for new Pokémon, while avoiding the likes of Team Rocket, as well as other evil organizations, as well as battling rivals, and meeting legendary Pokémon", ImgUrl = "https://m.media-amazon.com/images/M/MV5BNDcwZDc2NTEtMzU0Ni00YTQyLWIyYTQtNTI3YjM0MzhmMmI4XkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_FMjpg_UX1000_.jpg", Tags = "Action / Fantasy" });
                listAnime.Add(new Anime() { Name = "Mashle Magic and Muscles", Synopsis = "Magic land A place where anyone can use magic. A place where magical talent determines everything. In that land, Mach, a young boy who trains his body like crazy every day, lives in a forest far away from people. There is one secret. That is, he couldn't use magic. However, when the secret was known to others, Mush's life has completely changed!", ImgUrl = "https://m.media-amazon.com/images/M/MV5BM2M1Yzc5OTMtNWQxYS00NTg5LThiYjQtODRhZGMwODVkNjAyXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg", Tags = "Action / Fantasy" });
                listAnime.Add(new Anime() { Name = "Kamonohashi Ron no Kindan Suiri ", Synopsis = "Kamonohashi Ron, who was originally a genius at solving countless mysterious cases, was expelled from school and his detective license was confiscated. For the reason that he would pressure the criminal to commit suicide while solving the crime. Until one day A police detective from the investigation department had come to his house to earnestly request help. This flawed detective's thirst for solving cases is raging. He therefore agrees to help solve the case by acting as Isshiki Totomaru's brain.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYzg3N2Y3YTktNTVkOS00YTM5LTllNzItZDJkZjkwZmMzMWFmXkEyXkFqcGdeQXVyNjk1NzU1Mjk@._V1_FMjpg_UX1000_.jpg", Tags = "Mystery" });
                listAnime.Add(new Anime() { Name = "Kaichou wa Maid-sama!", Synopsis = "Our heroine, due to the misfortune of her father's debt, then disappears. So she had to live with her mother and younger sister. The reason why she came to study at this school Because the tuition fee is cheap But she had to face a big problem. Disorganization of male students in every aspect Whether it is about dressing that is not in order The cleanliness of the school, various problems, etc., so she rose through the ranks to become the first female student body president of the school. Seika High School to change this school for the better. according to her style", ImgUrl = "https://m.media-amazon.com/images/M/MV5BNWJkYzM4MWQtZWE2Mi00NmJkLTg5ZmUtNzNlMGYzOWYwYzE4XkEyXkFqcGdeQXVyNzQzNzQxNzI@._V1_FMjpg_UX1000_.jpg", Tags = "Romance / School" });
                listAnime.Add(new Anime() { Name = "Inuyasha", Synopsis = "Inuyasha is a half-demon. This makes Inuyasha unacceptable to both demons and normal humans. As a result, he needed the Four Spirit Orbs to become a full-fledged demon. The orb is protected by Kikyo, the village's sacred miko. Therefore, he and Kikyo often had to compete with each other. But Inuyasha couldn't hurt Kikyo just as Kikyo couldn't hurt Inuyasha either because they both had feelings for each other.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BNjQwZDcxOWYtMTc1ZS00OTYwLThhNmYtMjY3MjgxZGQzYTYzXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg", Tags = "Romance / Fantasy / Action" });
                listAnime.Add(new Anime() { Name = "Horimiya", Synopsis = "At first glance, the ultra-popular Kyoko Hori seems like a frivolous high school girl, but in reality, she's simple, pragmatic, and family-oriented. On the other hand, the bespectacled Miyamura Izumi comes across as an average, gloomy high school fanboy, but he's actually an attractive young man who has a bad-boy streak and is covered in piercings and tattoos. When these two unexpectedly si", ImgUrl = "https://m.media-amazon.com/images/M/MV5BMjBmMzJmN2UtNmEzNC00OGJmLTg4Y2EtMWNjYjlkOTZlZjAyXkEyXkFqcGdeQXVyMTIzNDEwODY@._V1_.jpg", Tags = "School / Romance" });
                listAnime.Add(new Anime() { Name = "Itazura na Kiss", Synopsis = "A cute girl (Aihara Kotoko) is in love with a smart and handsome guy who's a jerk in high school (Irie Naoki) and when her house is destroyed she moves with her father in to the Irie Family home where he starts to develop some feelings towards her.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BMWE5MzJlYjEtNGEzYS00NDcwLTkyNzktNDY1MjE1MDRkZDEyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_FMjpg_UX1000_.jpg", Tags = "Romance / Drama" });
                listAnime.Add(new Anime() { Name = "Kamisama Hajimemashita", Synopsis = "The story of Momozono Nanami, a high school girl who is going through a difficult time. Because her father ran away because of gambling debts, she was evicted from her apartment. One day, Nanami met The young man, Mikage, looked suspicious and said, \"I'll give you my house.\" Nanami went to the address she had given her. I found that it was just an abandoned shrine. And in that shrine there is still the young fox god Tomoe.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BZmE2NTBlY2QtNzNjYy00OGIxLTg2YWYtMTk0MWQwNDA2ZWQzXkEyXkFqcGdeQXVyMTUyNjc3NDQ4._V1_FMjpg_UX1000_.jpg", Tags = "Romance / Fantasy" });
                listAnime.Add(new Anime() { Name = "Ookami Shoujo to Kuro Ouji", Synopsis = "Shinohara Erika is a first year of high school student. While talking to her popular friends, she makes up a story about her \"boyfriend.\" But In reality, Erika doesn't have a boyfriend. Erika's popular friends soon begin to doubt her story and Erika is also running out of lies. Erika then sees a handsome boy on the street and takes his picture discreetly. She later shows his picture to her popular friends as her boyfriend. The boy in the picture is Sata Kyouya and happens to attend the same school as Her. She tells Kyouya about her situation and asks him to pretend to be her boyfriend. Even though Kyouya has a pretty appearance, he has a side no one knows about.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BY2Y5ZDFlZWMtNjhjYS00NzljLTk0OTYtMjNiODRkODg1MGU2XkEyXkFqcGdeQXVyMjI5MjU5OTI@._V1_FMjpg_UX1000_.jpg", Tags = "School / Romance" });
                break;

            case "Drama":
                listAnime.Add(new Anime() { Name = "Demon Slayer : Kimetsu No Yaiba", Synopsis = "Kamado Tanjiro is a gentle-hearted and intelligent boy. He therefore became the main source of income to support the family after his father died. Everything changes when a demon invades and kills Tanjiro's family. Only him and his younger sister Nezuko are left, who have turned into demons. But it was surprising that she still had human thoughts and expressions. After Tanjiro fought against Tomioka Giyu, a demon hunter who passed by. At Giyu's persuasion, he decided to become a demon hunter. To find a way to turn my sister back into a human being. and take revenge from the demon that killed his family members.", ImgUrl = "https://image.api.playstation.com/vulcan/ap/rnd/202106/1704/JzL1NLQvok7Pghe9W5PP2XNV.png", Tags = "Action" });
                listAnime.Add(new Anime() { Name = "YOASOBI : Idol", Synopsis = "The story tells of Goro, a young doctor in a rural hospital. He has such a passion for his idol, Hoshino Ai, that it could be called crazy. But one day, Goro meets Oshi. (our favorite idols) themselves in unexpected ways Because I had come to this far away hospital for prenatal care. Even though he was shocked at first, when he saw Ai's determination to continue \"lying\" in order to preserve both the idol's life and the lives of his unborn twin children, So he decided to help take care of her. including a promise to deliver the child safely", ImgUrl = "https://i1.sndcdn.com/artworks-nypVxQysyyck8wyt-wSzUwg-t500x500.jpg", Tags = "Idols / Music" });
                listAnime.Add(new Anime() { Name = "One Piece", Synopsis = "The story of the golden age of pirates The former owner of One Piece Gold D. Roger has surrendered. And accepted the death penalty and before dying Gold D. Roger left words before his death that changed the era of pirates: “My treasure? If you want it, take it. Go find it. I put everything in the world there. The pirates then headed towards the Grand Line to find the One Piece.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BM2YwYTkwNjItNGQzNy00MWE1LWE1M2ItOTMzOGI1OWQyYjA0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg", Tags = "Comedy / Fantasy / Action" });
                listAnime.Add(new Anime() { Name = "Kusuriya no Hitorigoto", Synopsis = "Mau Mau is a maid of honor who works in the royal palace. Before taking on this duty, she used to be a medicine man in the red light district, but was kidnapped and ended up living in a palace. The story begins when Mau Mau hears a rumor. Concerning the death of the emperor's heirs Curious nature and thirst for knowledge that has existed since time immemorial. Therefore, she was aroused to be interested and began to investigate the cause. In the end, what would be the fate of the young girl?", ImgUrl = "https://m.media-amazon.com/images/M/MV5BMWE4ZjAxNzQtMDI0Mi00OGFkLTkzMTAtMWExMWU2ZDE5NjIzXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg", Tags = "Mystery" });
                listAnime.Add(new Anime() { Name = "Kagami no Kojou", Synopsis = "Today is another day that Kokoro doesn't go to school. She kept herself locked in the dim bedroom. Suddenly, the large mirror emitted a strange light. When you reach out to touch She was sucked in. Mr. Anzai Kokoro, congratulations on being a guest of this castle the girl wearing the wolf mask said. At the end of the world behind the glass is a magical castle. There were six other children there who met the same fate as Kokoro. They must find a hidden key. Whoever finds it can make any wish they wish.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYTNmYWIwOWUtNzk0ZC00MjVmLTkyOWYtZGZhYTMwNTAxYTE5XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg", Tags = "Mystery / Fantasy" });
                listAnime.Add(new Anime() { Name = "Detective Conan", Synopsis = "Hiroki Sawada was a 10-age kid who got into a US college and even graduated. One day, Hiroki finished A.I. Noah-sue-ark and suicide to end his life. 2 years later. Conan and Rachel and Genta,Ayumi,Mitsuhiko,Haibara finally able to play Cocoon but Noah-Sue-Ark modified the program and made Cocoon more and more harsh and difficult with these 5 scenes: Viking. Paris Dakari Race. Colosseum. Solomen Treasures. 1888 London. The condition the Noah Ark altered was the 50 kids must be able to have one survived or else none of them can survive in real world if all got killed. Which scenario would Conan choose, and what would happen?", ImgUrl = "https://m.media-amazon.com/images/M/MV5BZmMxNGE0YjEtYTVkMC00ZGVjLWI3OTEtODY0N2I0NGU0ZjQ0XkEyXkFqcGdeQXVyMTA0MTM5NjI2._V1_.jpg", Tags = "Adventure / Mystery" });
                listAnime.Add(new Anime() { Name = "Itazura na Kiss", Synopsis = "A cute girl (Aihara Kotoko) is in love with a smart and handsome guy who's a jerk in high school (Irie Naoki) and when her house is destroyed she moves with her father in to the Irie Family home where he starts to develop some feelings towards her.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BMWE5MzJlYjEtNGEzYS00NDcwLTkyNzktNDY1MjE1MDRkZDEyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_FMjpg_UX1000_.jpg", Tags = "Comedy / Romance" });
                break;

            case "Romance":
                listAnime.Add(new Anime() { Name = "Sword Art Online", Synopsis = "Kirigaya Kazuto joins a virtual reality game called Sword Art Online or SAO. When he plays, he finds himself unable to log out of the game. But the only way out of this game is to successfully clear the game. Or over in the game means the actual death of the player. Therefore, to meet the conditions of clearing this game and leaving the virtual world. Kazuto must clear this game successfully. Or he will meet death!", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYjY4MDU2YjMtNzY1MC00ODg1LWIwMzYtMWE5YTA3YTI4ZjMxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg", Tags = "Fantasy / Adventure / Action" });
                listAnime.Add(new Anime() { Name = "Kaichou wa Maid-sama!", Synopsis = "Our heroine, due to the misfortune of her father's debt, then disappears. So she had to live with her mother and younger sister. The reason why she came to study at this school Because the tuition fee is cheap But she had to face a big problem. Disorganization of male students in every aspect Whether it is about dressing that is not in order The cleanliness of the school, various problems, etc., so she rose through the ranks to become the first female student body president of the school. Seika High School to change this school for the better. according to her style", ImgUrl = "https://m.media-amazon.com/images/M/MV5BNWJkYzM4MWQtZWE2Mi00NmJkLTg5ZmUtNzNlMGYzOWYwYzE4XkEyXkFqcGdeQXVyNzQzNzQxNzI@._V1_FMjpg_UX1000_.jpg", Tags = "Comedy / School" });
                listAnime.Add(new Anime() { Name = "Inuyasha", Synopsis = "Inuyasha is a half-demon. This makes Inuyasha unacceptable to both demons and normal humans. As a result, he needed the Four Spirit Orbs to become a full-fledged demon. The orb is protected by Kikyo, the village's sacred miko. Therefore, he and Kikyo often had to compete with each other. But Inuyasha couldn't hurt Kikyo just as Kikyo couldn't hurt Inuyasha either because they both had feelings for each other.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BNjQwZDcxOWYtMTc1ZS00OTYwLThhNmYtMjY3MjgxZGQzYTYzXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg", Tags = "Comedy / Fantasy / Action" });
                listAnime.Add(new Anime() { Name = "Horimiya", Synopsis = "At first glance, the ultra-popular Kyoko Hori seems like a frivolous high school girl, but in reality, she's simple, pragmatic, and family-oriented. On the other hand, the bespectacled Miyamura Izumi comes across as an average, gloomy high school fanboy, but he's actually an attractive young man who has a bad-boy streak and is covered in piercings and tattoos. When these two unexpectedly si", ImgUrl = "https://m.media-amazon.com/images/M/MV5BMjBmMzJmN2UtNmEzNC00OGJmLTg4Y2EtMWNjYjlkOTZlZjAyXkEyXkFqcGdeQXVyMTIzNDEwODY@._V1_.jpg", Tags = "School / Comedy" });
                listAnime.Add(new Anime() { Name = "Itazura na Kiss", Synopsis = "A cute girl (Aihara Kotoko) is in love with a smart and handsome guy who's a jerk in high school (Irie Naoki) and when her house is destroyed she moves with her father in to the Irie Family home where he starts to develop some feelings towards her.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BMWE5MzJlYjEtNGEzYS00NDcwLTkyNzktNDY1MjE1MDRkZDEyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_FMjpg_UX1000_.jpg", Tags = "Comedy / Drama" });
                listAnime.Add(new Anime() { Name = "Kamisama Hajimemashita", Synopsis = "The story of Momozono Nanami, a high school girl who is going through a difficult time. Because her father ran away because of gambling debts, she was evicted from her apartment. One day, Nanami met The young man, Mikage, looked suspicious and said, \"I'll give you my house.\" Nanami went to the address she had given her. I found that it was just an abandoned shrine. And in that shrine there is still the young fox god Tomoe.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BZmE2NTBlY2QtNzNjYy00OGIxLTg2YWYtMTk0MWQwNDA2ZWQzXkEyXkFqcGdeQXVyMTUyNjc3NDQ4._V1_FMjpg_UX1000_.jpg", Tags = "Comedy / Fantasy" });
                listAnime.Add(new Anime() { Name = "Ookami Shoujo to Kuro Ouji", Synopsis = "Shinohara Erika is a first year of high school student. While talking to her popular friends, she makes up a story about her \"boyfriend.\" But In reality, Erika doesn't have a boyfriend. Erika's popular friends soon begin to doubt her story and Erika is also running out of lies. Erika then sees a handsome boy on the street and takes his picture discreetly. She later shows his picture to her popular friends as her boyfriend. The boy in the picture is Sata Kyouya and happens to attend the same school as Her. She tells Kyouya about her situation and asks him to pretend to be her boyfriend. Even though Kyouya has a pretty appearance, he has a side no one knows about.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BY2Y5ZDFlZWMtNjhjYS00NzljLTk0OTYtMjNiODRkODg1MGU2XkEyXkFqcGdeQXVyMjI5MjU5OTI@._V1_FMjpg_UX1000_.jpg", Tags = "School / Comedy" });
                listAnime.Add(new Anime() { Name = "Kyokou Suiri", Synopsis = "When she was still just a girl, Kotoko was kidnapped by the spirits that asked her to become a mediator between the two worlds, as well as the Goddess of Wisdom for these spirits. However, power always comes with a price: an eye and a leg. Now, years later, watching out for dangerous spirits, helping the good spirits, Kotoko meets a mysterious young man named Kurou and immediately takes an interest in him. How can spirits be afraid of a single human and what secrets does Kurou hide?", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYzBmNjIxMDktMjk2MS00MjA0LTljYjQtZWNiYjM2YmU3Y2E1XkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg", Tags = "Mystery" });
                break;

            case "Mystery":
                listAnime.Add(new Anime() { Name = "Kusuriya no Hitorigoto", Synopsis = "Mau Mau is a maid of honor who works in the royal palace. Before taking on this duty, she used to be a medicine man in the red light district, but was kidnapped and ended up living in a palace. The story begins when Mau Mau hears a rumor. Concerning the death of the emperor's heirs Curious nature and thirst for knowledge that has existed since time immemorial. Therefore, she was aroused to be interested and began to investigate the cause. In the end, what would be the fate of the young girl?", ImgUrl = "https://m.media-amazon.com/images/M/MV5BMWE4ZjAxNzQtMDI0Mi00OGFkLTkzMTAtMWExMWU2ZDE5NjIzXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg", Tags = "Drama" });
                listAnime.Add(new Anime() { Name = "Kamonohashi Ron no Kindan Suiri ", Synopsis = "Kamonohashi Ron, who was originally a genius at solving countless mysterious cases, was expelled from school and his detective license was confiscated. For the reason that he would pressure the criminal to commit suicide while solving the crime. Until one day A police detective from the investigation department had come to his house to earnestly request help. This flawed detective's thirst for solving cases is raging. He therefore agrees to help solve the case by acting as Isshiki Totomaru's brain.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYzg3N2Y3YTktNTVkOS00YTM5LTllNzItZDJkZjkwZmMzMWFmXkEyXkFqcGdeQXVyNjk1NzU1Mjk@._V1_FMjpg_UX1000_.jpg", Tags = "Comedy" });
                listAnime.Add(new Anime() { Name = "Kagami no Kojou", Synopsis = "Today is another day that Kokoro doesn't go to school. She kept herself locked in the dim bedroom. Suddenly, the large mirror emitted a strange light. When you reach out to touch She was sucked in. Mr. Anzai Kokoro, congratulations on being a guest of this castle the girl wearing the wolf mask said. At the end of the world behind the glass is a magical castle. There were six other children there who met the same fate as Kokoro. They must find a hidden key. Whoever finds it can make any wish they wish.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYTNmYWIwOWUtNzk0ZC00MjVmLTkyOWYtZGZhYTMwNTAxYTE5XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg", Tags = "Drama / Fantasy" });
                listAnime.Add(new Anime() { Name = "Attack on Titan", Synopsis = "Humans are nearly exterminated by giant creatures called Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a land protected by extremely high walls, even taller than the biggest of titans. Flash forward to the present, and mankind has not seen a titan in over 100 years. One day, 10 year old Eren and his childhood friend Mikasa witness something horrific as the city walls are destroyed by a colossal titan that appears out of thin air. As the smaller titans flood the city, the two kids watch in horror as Eren's mother is eaten alive. Eren vows that he will murder every single titan and take revenge for all of mankind.", ImgUrl = "https://s.isanook.com/mv/0/ud/10/53513/2.jpg", Tags = "Adventure / Action" });
                listAnime.Add(new Anime() { Name = "Detective Conan", Synopsis = "Hiroki Sawada was a 10-age kid who got into a US college and even graduated. One day, Hiroki finished A.I. Noah-sue-ark and suicide to end his life. 2 years later. Conan and Rachel and Genta,Ayumi,Mitsuhiko,Haibara finally able to play Cocoon but Noah-Sue-Ark modified the program and made Cocoon more and more harsh and difficult with these 5 scenes: Viking. Paris Dakari Race. Colosseum. Solomen Treasures. 1888 London. The condition the Noah Ark altered was the 50 kids must be able to have one survived or else none of them can survive in real world if all got killed. Which scenario would Conan choose, and what would happen?", ImgUrl = "https://m.media-amazon.com/images/M/MV5BZmMxNGE0YjEtYTVkMC00ZGVjLWI3OTEtODY0N2I0NGU0ZjQ0XkEyXkFqcGdeQXVyMTA0MTM5NjI2._V1_.jpg", Tags = "Adventure / Drama" });
                listAnime.Add(new Anime() { Name = "Kyokou Suiri", Synopsis = "When she was still just a girl, Kotoko was kidnapped by the spirits that asked her to become a mediator between the two worlds, as well as the Goddess of Wisdom for these spirits. However, power always comes with a price: an eye and a leg. Now, years later, watching out for dangerous spirits, helping the good spirits, Kotoko meets a mysterious young man named Kurou and immediately takes an interest in him. How can spirits be afraid of a single human and what secrets does Kurou hide?", ImgUrl = "https://m.media-amazon.com/images/M/MV5BYzBmNjIxMDktMjk2MS00MjA0LTljYjQtZWNiYjM2YmU3Y2E1XkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg", Tags = "Action" });
                listAnime.Add(new Anime() { Name = "Darwin’s Game", Synopsis = "Darwin's Game focuses on 17-year old Kaname Sudou, who accepts an online invitation from a friend to play a mobile game called Darwin's Game. He had no idea that the game involves a fight between the two players and you might actually die both in the game and in real life. To win the fight, players are given a Sigil, an evolutionary ability that varies from player to player and only the most skillful players will be able to clear the game and survive. Kaname determines to clear the game, find the creators of the game and take revenge upon them.", ImgUrl = "https://m.media-amazon.com/images/M/MV5BNzdhOGUwNjEtNTQyMi00MjkxLThkNDMtYjZiZmVkYWI2NDllXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_FMjpg_UX1000_.jpg", Tags = "Action" });
                break;
        }

        return listAnime;
    }
}
